import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import Dummy from '@/component/dummy'
// import styles1 from '../styles/Home1.module.css'
// import styles2 from '../styles/Home2.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Dummy/>
      {/* <style jsx>
        {`
        .myspan{
        background-color: blue
        }
        `}
      </style> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

{/* 
      <h1 className={styles1.cont}>Hello</h1>
      <h1 className={styles2.cont}>Hello World</h1> */}

      {/* <Script src="/sc.js" strategy='lazyOnload'></Script> */}

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          
          {/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158}/> */}
          <img className={styles.myImg} src="/homeimg.jfif" width={237} height={158} alt="hunting coder" />
        </div>
        <h1 className={styles.title}>
          <span className='dummy'>&lt;HuntingCoder/&gt;</span>
        </h1>

       
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}